version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'bf'
    ports:
      - 5433:5433
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'